AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Parameters:
  CloudDbUrl:
    Type: String
  CloudDbUser:
    Type: String
  CloudDbPassword:
    Type: String
    NoEcho: true

Resources:
  RetailSyncApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/retailsync-api-0.0.1-SNAPSHOT.jar
      Handler: com.aximly.retailsync_api.StreamLambdaHandler::handleRequest
      Runtime: java17
      Environment:
        Variables:
          CLOUD_DB_URL: !Ref CloudDbUrl
          CLOUD_DB_USER: !Ref CloudDbUser
          CLOUD_DB_PASSWORD: !Ref CloudDbPassword
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY